name: CI Testing

on:
  push:
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install FE deps
        working-directory: frontend
        run: npm install

      - name: Run FE tests
        working-directory: frontend
        env:
          CI: true
        run: npm test -- --coverage

      - name: Upload FE Coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install BE deps
        working-directory: backend
        run: npm install

      - name: Run BE tests
        working-directory: backend
        run: npm test -- --coverage

      - name: Upload BE Coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage
